### consultar todos los productos
GET http://localhost:1234/products

### obtener producto por id
GET http://localhost:1234/products/2

### crear un producto
POST http://localhost:1234/products
Content-Type: application/json

{   
    "id_category": 1,
	"title": "zapatillas nike",
    "description": "zapatillas nike deportivas",
    "price": 125,
    "image": "https://nikearprod.vtexassets.com/arquivos/ids/699302/DD9283_001_A_PREM.jpg?v=638229666904000000"
}

### borrar un producto
DELETE http://localhost:1234/products/23

### actualizar un producto
PATCH http://localhost:1234/products/1
Content-Type: application/json

{   
    "price": 115
}

### consultar todas las categorias
GET http://localhost:1234/categories

### obtener categoria por id
GET http://localhost:1234/categories/3

### crear categoria
POST http://localhost:1234/categories
Content-Type: application/json

{
    "category": "asd"
}

### borrar una categoria
DELETE http://localhost:1234/categories/4

### actualizar una categoria
PATCH http://localhost:1234/categories/1
Content-Type: application/json

{   
    "category": "Zapatillas"
}

### obtener todos los usuarios
GET http://localhost:1234/users

### obtener un usuario por id
GET http://localhost:1234/users/1

### obtener un usuario por email y password
GET http://localhost:1234/users?email=jere@mail.com&password=jere1234

###
GET http://localhost:1234/users?email=asdasd@mail.com

### actualizar un usuario
patch http://localhost:1234/users/1
Content-Type: application/json

{   
    "password": "jere1234"
}


### agregar un usuario
POST http://localhost:1234/users
Content-Type: application/json

{   
    "email" : "marrok@mail.com",
    "password": "marrok1234",
    "userName": "marrok"
}


